[package]
name = "gray-hole-client"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gray-hole-lib = {path = "../gray-hole-lib"}
anyhow = "1.0.66"
